apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: adapter
    app.kubernetes.io/instance: fint-utdanning-kodeverk-adapter_rogfk_no
    app.kubernetes.io/name: fint-utdanning-kodeverk-adapter
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: rogfk.no
    fintlabs.no/team: core
  name: fint-utdanning-kodeverk-adapter
  namespace: rogfk-no
spec:
  env:
  - name: JAVA_TOOL_OPTIONS
    value: -XX:+ExitOnOutOfMemoryError -Xmx384M
  - name: fint.adapter.base-url
    value: https://api.felleskomponent.no
  - name: fint.fylkesnr
    value: "11"
  - name: fint.adapter.id
    value: https://vigoiks.no/rogfk-no/utdanning/kodeverk
  envFrom:
  - secretRef:
      name: utdanning-kodeverk-adapter
  image: ghcr.io/fintlabs/fint-utdanning-kodeverk-adapter:sha-0000000
  imagePullPolicy: Always
  onePassword:
    itemPath: vaults/aks-api-vault/items/fint-utdanning-kodeverk-adapter
  orgId: rogfk.no
  port: 8080
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  restartPolicy: Always
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
---
apiVersion: fintlabs.no/v1alpha1
kind: FintAdapter
metadata:
  labels:
    app.kubernetes.io/component: adapter
    app.kubernetes.io/instance: fint-utdanning-kodeverk-adapter_rogfk_no
    app.kubernetes.io/name: fint-utdanning-kodeverk-adapter
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: rogfk.no
    fintlabs.no/team: core
  name: utdanning-kodeverk-adapter
  namespace: rogfk-no
spec:
  components:
  - utdanning_kodeverk
  note: Sender OTStatus og OTEnhet til FINT
  orgId: rogfk.no
