fint:
  adapter:
    id: https://vigoiks.no/fintlabs-no/utdanning/kodeverk-test
    password:
    username:
    base-url: http://localhost:8081
#    base-url: https://alpha.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 1
    capabilities:
      otstatus:
        domain-name: utdanning
        packageName: kodeverk
        resource-name: otstatus
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      otenhet:
        domain-name: utdanning
        packageName: kodeverk
        resource-name: otenhet
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE

spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-adapter openid
