apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-utdanning-kodeverk-adapter
  app.kubernetes.io/instance: fint-utdanning-kodeverk-adapter_fintlabs-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-flyt
  fintlabs.no/team: flyt
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-utdanning-kodeverk-adapter_fintlabs_no"
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "https://beta.felleskomponent.no"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-beta-vault/items/fint-utdanning-kodeverk-adapter"
    target:
      kind: Application
      name: fint-utdanning-kodeverk-adapter

